import { RouterProvider, createRouter } from '@tanstack/react-router'

// This file is auto-generated by TanStack Router
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

function App() {
  return <RouterProvider router={router} />
}

export default App
