/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarkChapterIdVerseIdRouteImport } from './routes/mark.$chapterId.$verseId'
import { Route as BibleBookChapterIdVerseIdRouteImport } from './routes/bible.$book.$chapterId.$verseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkChapterIdVerseIdRoute = MarkChapterIdVerseIdRouteImport.update({
  id: '/mark/$chapterId/$verseId',
  path: '/mark/$chapterId/$verseId',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleBookChapterIdVerseIdRoute =
  BibleBookChapterIdVerseIdRouteImport.update({
    id: '/bible/$book/$chapterId/$verseId',
    path: '/bible/$book/$chapterId/$verseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mark/$chapterId/$verseId': typeof MarkChapterIdVerseIdRoute
  '/bible/$book/$chapterId/$verseId': typeof BibleBookChapterIdVerseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mark/$chapterId/$verseId': typeof MarkChapterIdVerseIdRoute
  '/bible/$book/$chapterId/$verseId': typeof BibleBookChapterIdVerseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mark/$chapterId/$verseId': typeof MarkChapterIdVerseIdRoute
  '/bible/$book/$chapterId/$verseId': typeof BibleBookChapterIdVerseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mark/$chapterId/$verseId'
    | '/bible/$book/$chapterId/$verseId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mark/$chapterId/$verseId' | '/bible/$book/$chapterId/$verseId'
  id:
    | '__root__'
    | '/'
    | '/mark/$chapterId/$verseId'
    | '/bible/$book/$chapterId/$verseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarkChapterIdVerseIdRoute: typeof MarkChapterIdVerseIdRoute
  BibleBookChapterIdVerseIdRoute: typeof BibleBookChapterIdVerseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mark/$chapterId/$verseId': {
      id: '/mark/$chapterId/$verseId'
      path: '/mark/$chapterId/$verseId'
      fullPath: '/mark/$chapterId/$verseId'
      preLoaderRoute: typeof MarkChapterIdVerseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible/$book/$chapterId/$verseId': {
      id: '/bible/$book/$chapterId/$verseId'
      path: '/bible/$book/$chapterId/$verseId'
      fullPath: '/bible/$book/$chapterId/$verseId'
      preLoaderRoute: typeof BibleBookChapterIdVerseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarkChapterIdVerseIdRoute: MarkChapterIdVerseIdRoute,
  BibleBookChapterIdVerseIdRoute: BibleBookChapterIdVerseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
